# Generated by Django 5.1 on 2024-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
