# Generated by Django 5.1 on 2024-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
