# Generated by Django 5.1 on 2024-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, upload_to='blog')),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
