# Generated by Django 5.1 on 2024-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
